name: Lambda Deploy Pipeline

on:
  push:
    branches:
      - main   
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies & package
        run: |
          rm -rf package
          mkdir package
          if [ -s requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt -t package
          fi
          cp lambda_function.py package/
          (cd package && zip -r ../lambda.zip .)
          ls -lh lambda.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      - name: Deploy Lambda
        env:
          LAMBDA_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        run: |
          echo "Deploying to Lambda: $LAMBDA_NAME"
          aws lambda update-function-code --function-name "$LAMBDA_NAME" --zip-file fileb://lambda.zip
          echo "Deployment complete!"
